### ISSUE TITLE
Pusher action 'trigger' returning empty hash instead of true

### ISSUE THREAD

**Issue by madhusudhan518** [stevegraham/slanger#187]
when i am trying to trigger an event , it is returning empty hash instead of true

**Comment by markburns** [comment]
With what library? JS?

**Comment by madhusudhan518** [comment]
Hi @markburns  i am using
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script src="/pusher.js"></script>
<script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
<script src="/jquery.titlealert.js"></script>

**Comment by markburns** [comment]
So you opened this issue on pusher, https://github.com/pusher/pusher-http-ruby/issues/74 then closed it because of a presumably satisfactory answer from them?

I guess we do the same thing as pusher. Not sure what you are expecting here.

It isn't good form to ask the pusher guys for help if you are only using slanger.

**Comment by madhusudhan518** [comment]
yes, i  got the answer . Next time i won't do that.
Thank you for your reply @markburns .........
